apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-storage
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@playalvis.com
    privateKeySecretRef:
      name: letsencrypt-production-storage
    solvers:
      - http01:
          ingress:
            class: nginx