apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-local-user
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: support@palnesto.biz
    privateKeySecretRef:
      name: letsencrypt-local-user
    solvers:
      - http01:
          ingress:
            class: nginx